version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: swapi_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: starwars
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d starwars"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: swapi_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE_NAME: starwars
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  migrate:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.migrate
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE_NAME: starwars
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - migrate

  adminer:
    image: adminer
    container_name: swapi_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
